Adds email notification if failure occurs
harvard-lts/epadd-curator-app pull request #22
Opened 2023-04-13 18:10 UTC by ives1227

**Uses the lts-mqemailnotifier to send a message to the queue to trigger the dais-notifier*
* * *

**Ticket Link**: https://jira.huit.harvard.edu/browse/LTSEPADD-93

* Other Relevant Links (Mailing list discussion, related pull requests, etc.)
MQ Email Notifier Module: https://github.com/harvard-lts/mq_email_notifier

# How should this be tested?

Follow testing instructions here: https://github.com/harvard-lts/epadd-curator-app#running-tests

You can also upload a packet with the drsConfig.txt removed to NextCloud Dev (if you have access).  Curator app fails if no drsConfig.txt is found so an email should be sent out.

# Test coverage
Yes/No: Are changes in this pull-request covered by:
- unit tests? yes
- integration tests? yes (unfortunately bundled with unit tests)

2023-04-14 03:18 UTC, awoods requested changes

2023-04-14 03:18 UTC, awoods commented on app/monitor_exports/__init__.py
> +    delmiter = ""
Typo: 'delmiter'. 

Line:185 may hit a `null` error.

2023-04-15 21:20 UTC, ives1227 commented on app/monitor_exports/__init__.py
> +    delmiter = ""
Good catch

2023-04-15 21:21 UTC, ives1227 commented on requirements.txt
> +lts-mqemailnotifier
It is published here right now: https://test.pypi.org/manage/project/lts-mqemailnotifier/release/0.0.2/ - I changed it to specify a number

2023-04-17 00:01 UTC, awoods approved these changes
Looks good.

Separately, can you point me to the documentation you use for publishing Python artifacts. See: https://github.com/harvard-lts/epadd-curator-app/pull/22#discussion_r1167639224

2023-04-17 00:02 UTC, merged

2023-04-17 00:03 UTC, ives1227 commented
@awoods publishing the artifact is in the Readme of the utility here: https://github.com/harvard-lts/mq_email_notifier#7-build-and-publish-the-package